"""
Django settings for DjangoBlog project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 先把项目根目录下的 .env 读进环境变量（数据库密码、SECRET_KEY 等敏感配置）。
# .env 已在 .gitignore 里忽略，不会进版本库；没有这个文件也不影响启动
# （SQLite 模式 / 用系统环境变量时不需要它）。
from .env_loader import load_env_file          # noqa: E402

load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 部署到公网请通过环境变量 DJANGO_SECRET_KEY（或 .env）提供自己的密钥。
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    # 下面这串只用于本地开发 / 演示；公开仓库里放它不影响安全，
    # 因为它只用来签名 session，且生产环境会被环境变量覆盖。
    'django-insecure-dev-only-key-change-me-in-production-0e6v$2k9m4x1p',
)

# SECURITY WARNING: don't run with debug turned on in production!
# 本地调试可以设置环境变量 DJANGO_DEBUG=1 打开 DEBUG（会显示详细报错页）
DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoBlog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# 默认使用 MySQL（保持原有配置不变）；把环境变量 DB_ENGINE 设为 sqlite
# 即可切到本地 SQLite，方便在没有 MySQL 的机器上跑起来 / 做自动化测试：
#     Windows PowerShell:  $env:DB_ENGINE="sqlite"; python manage.py runserver
#     Linux / macOS:       DB_ENGINE=sqlite python manage.py runserver

DB_ENGINE = os.environ.get('DB_ENGINE', 'mysql').lower()

if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'myblog_db'),        # 数据库名
            'USER': os.environ.get('DB_USER', 'root'),             # 数据库用户名
            # 密码不再硬编码：写在项目根目录的 .env 里（已 gitignore），
            # 或者用环境变量 DB_PASSWORD 提供。留空时会给出明确提示。
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),        # 数据库主机
            'PORT': os.environ.get('DB_PORT', '3306'),             # 数据库端口
            'OPTIONS': {
                'charset': 'utf8mb4',  # 设置字符集为utf8mb4，支持emoji
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 设置SQL模式
                'connect_timeout': 5,  # 数据库没启动时快速失败，而不是长时间卡住
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'   # collectstatic 的输出目录（部署时用）

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

# 评论 / 图片上传限制
COMMENT_MAX_LENGTH = 1000
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024      # 单次请求最大 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# 分页
POSTS_PER_PAGE = 6
COMMENTS_PER_PAGE = 10
COMMENT_REPLY_PREVIEW = 3      # 楼中楼默认展示的回复条数，其余折叠

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 让 PyMySQL 冒充 MySQLdb，这样不用额外编译 mysqlclient 也能连 MySQL。
# 如果没装 PyMySQL，给出明确的提示，而不是等到连接数据库时抛一句难懂的 ImportError。
if DB_ENGINE != 'sqlite':
    try:
        import pymysql

        pymysql.install_as_MySQLdb()
    except ImportError as exc:      # pragma: no cover - 只在本机环境缺失时触发
        raise ImportError(
            '连接 MySQL 需要 PyMySQL 驱动，请先安装：\n'
            '    pip install -r requirements.txt\n'
            '或者临时改用 SQLite 运行：\n'
            '    $env:DB_ENGINE="sqlite"; python manage.py runserver'
        ) from exc
